### ISSUE TITLE
What data is being sent to dock.karthikv.net

### ISSUE THREAD

**Issue by siderakis** [karthikv/tradeship#4]
Is this feature required? can it be turned off?

**Comment by karthikv** [comment]
Tradeship needs to know aliases for dependencies (e.g. `$` for jQuery, `_` for lodash/underscore, `test` for ava, etc.) so it can find the correct library to import when these names are used. We've accomplished this by analyzing more than 100 GB of public JS code on GitHub, and dock.karthikv.net stores this alias data.

The request to dock.karthikv.net contains the names of each package.json dependency, and it returns the aliases. For instance, see https://dock.karthikv.net/load?ids=jquery,underscore to find aliases of jquery and underscore.

You can find the code that makes this request at https://github.com/karthikv/tradeship/blob/f91740b5d35cf1ee144b073e17b1a5fa2919583e/lib/dep-registry.js#L245-L275

This data really helps with the user experience, so it's the default behavior. Since tradeship piggybacks off other configuration files like eslint, instead of having its own, there's no option to disable this currently.

I'm closing this issue, but if you have any further questions/concerns, feel free to ask them here!
